#  Instruction: https://redefine-docs.ohevan.com/zh/getting-started

info:
  title: Dozy Memory
  subtitle: ZDY's Blog
  author: Deyang Zeng
  url: https://hexo.io

defaults:
  favicon: /images/d.ico
  logo: /images/d.png
  avatar: /images/d.png

colors:
  primary: "#006000"
  secondary:
  default_mode: dark

global:
  fonts:
    chinese:
      enable: false
      family:
      url:
    english:
      enable: false
      family:
      url:
    title:
      enable: false
      family:
      url:
  content_max_width: 1000px
  sidebar_width: 210px
  hover:
    shadow: true
    scale: true
  scroll_progress:
    bar: true
    percentage: true
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true # site page view
    site_uv: true # site unique visitor
    post_pv: true # post page view
  single_page: true
  open_graph:
    enable: true
    image: /images/redefine-og.webp  # default og:image
    description: Hexo Theme Redefine, Redefine Your Hexo Journey.
  preloader:
    enable: true
    custom_message: Dozy Memory | Blog on Tech & Life
  side_tools:
    gear_rotation: true
    auto_expand: false
  google_analytics:
    enable: false
    id:

fontawesome: # Pro v6.2.1
  thin: false
  light: false
  duotone: true
  sharp_solid: false

home_banner:
  enable: true
  style: fixed # static or fixed
  image:
    light: /images/light.png
    dark: /images/dark.png
  title: Dozy Memory | Blog on Tech & Life
  subtitle:
    text: ["Fragments of a Curious Mind", "Aim to be a confident ROBOT ENGINEER",] # subtitle text, array
    hitokoto:  # 一言配置
      enable: false # Whether to enable hitokoto
      show_author: false # Whether to show author
      api: https://v1.hitokoto.cn # API URL, can add types, see https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
    smart_backspace: true
  text_color:
    light: "#ffffff"
    dark: "#e3e3e3"
  text_style:
    title_size: 2.8rem
    subtitle_size: 1.5rem
    line_height: 1.2
  custom_font:
    enable: false
    family:
    url:
  social_links:
    enable: true
    style: default # default, reverse, center
    links:
      github:  https://github.com
      instagram: https://www.instagram.com
      email:  derekzane13@gmail.com
#      zhihu:  # your ZhiHu URL
#      twitter:  # your twitter URL
    qrs:
      weixin: /images/qr_wechat.jpg

navbar:
  auto_hide: true
  color:
    left: "#000000"
    right: "#000000"
    transparency: 35
  width:
    home: 1200px
    pages: 1000px
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Archives:
      path: /archives
      icon: fa-regular fa-archive
    Categories:
      path: /categories
      icon: fa-regular fa-folder
    Bookmarks:
      path: /bookmarks/
      icon: fa-solid fa-bookmark
#    About:
#      icon: fa-regular fa-user
#      submenus:
#        Me: /about
#        Github: https://github.com
#        instagram: https://instagram.com
#        Blog: /blog
#    Links:
#       icon: fa-regular fa-link
#       submenus:
#         Link1: /link1
#         Link2: /link2
#         Link3: /link3
#    Status:
#      path: https://status.ohevan.com/
#      icon: fa-regular fa-chart-bar

#  $ npm i hexo-generator-searchdb
  search:
    enable: true
    preload: true

home:
  sidebar:
    enable: true
    position: right
    first_item: info # menu, info
    announcement: Announcement text
    show_on_mobile: true
    links:
      About:
        path: /about
        icon: fa-regular fa-user
      Tags:
        path: /tags
        icon: fa-regular fa-tags
      Categories:
        path: /categories
        icon: fa-regular fa-folder
      Archives:
        path: /archives
        icon: fa-regular fa-archive
  article_date_format: YYYY-MM-DD # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss.
  excerpt_length: 200
  categories:
    enable: true
    limit: 3
  tags:
    enable: true
    limit: 3

articles:
  style:
    font_size: 16px
    line_height: 1.5
    image_border_radius: 14px
    image_alignment: center
    image_caption: false
    link_icon: true
    delete_mask: false
    title_alignment: left # left, center
    headings_top_spacing:
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  #  $ npm install hexo-wordcount
  word_count:
    enable: true
    count: true
    min2read: true
  author_label:
    enable: false
    auto: false # automatically add author label, e.g. Lv1, Lv2, Lv3...
    list: []
  code_block:
    copy: true
    style: simple # mac, simple
    highlight_theme:
      light: github # github, atom-one-light, default
      dark: vs2015 # github-dark, monokai-sublime, vs2015, night-owl, atom-one-dark, nord, tokyo-night-dark, a11y-dark, agate
    font:
      enable: false
      family:
      url:
  # Table of contents
  toc:
    enable: true
    max_depth: 3
    number: true # add number automatically
    expand: true
    init_open: true
  copyright:
    enable: true
    default: all_rights_reserved # cc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  lazyload: true
  # Pangu.js (automatically add space between Chinese and English)
  pangu_js: false
  #  $ npm install nodejieba. Transplanted from hexo-theme-volantis.
  recommendation:
    enable: false
    title: 推荐阅读
    limit: 3
    mobile_limit: 2
    placeholder: /images/wallhaven-wqery6-light.webp
    skip_dirs: []

comment:
  enable: true
  system: gitalk # waline, gitalk, twikoo, giscus
  config:
    gitalk:
      clientID: Ov23liaRSjcF59RLX09N # GitHub Application Client ID
      clientSecret: da73606dbe16ecea7580e3d2576013e7b923803c # GitHub Application Client Secret
      repo: comment_gitalk # GitHub repository
      owner: dozybot001 # GitHub repository owner
      proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # GitHub repository proxy
# Waline comment system. See https://waline.js.org/
#    waline:
#      serverUrl: https://example.example.com # Waline server URL. e.g. https://example.example.com
#      lang: zh-CN # Waline language. e.g. zh-CN, en-US. See https://waline.js.org/guide/client/i18n.html
#      emoji: [] # Waline emojis, see https://waline.js.org/guide/features/emoji.html
#      recaptchaV3Key: # Google reCAPTCHA v3 key. See https://waline.js.org/reference/client/props.html#recaptchav3key
#      turnstileKey: # Turnstile key. See https://waline.js.org/reference/client/props.html#turnstilekey
#      reaction: false # Waline reaction. See https://waline.js.org/reference/client/props.html#reaction
#    # Gitalk comment system. See https://github.com/gitalk/gitalk
# Twikoo comment system. See https://twikoo.js.org/
#    twikoo:
#      version: 1.6.10 # Twikoo version, do not modify if you don't know what it is
#      server_url: # Twikoo server URL. e.g. https://example.example.com
#      region: # Twikoo region. can be empty
# Giscus comment system. See https://giscus.app/
#    giscus:
#      repo: # Github repository name e.g. EvanNotFound/hexo-theme-redefine
#      repo_id: # Github repository id
#      category: # Github discussion category
#      category_id: # Github discussion category id
#      mapping: pathname # Which value to use as the unique identifier for the page. e.g. pathname, url, title, og:title. DO NOT USE og:title WITH PJAX ENABLED since pjax will not update og:title when the page changes
#      strict: 0 # Whether to enable strict mode. e.g. 0, 1
#      reactions_enabled: 1 # Whether to enable reactions. e.g. 0, 1
#      emit_metadata: 0 # Whether to emit metadata. e.g. 0, 1
#      lang: en # Giscus language. e.g. en, zh-CN, zh-TW
#      input_position: bottom # Place the comment box above/below the comments. e.g. top, bottom
#      loading: lazy # Load the comments lazily

footer:
  runtime: true
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  start: 2025/10/13 20:02:33
  statistics: true # total articles, total words
  customize: 歌未竟，东方白 | Songs unsung, a brand new dawn.
  # https://beian.miit.gov.cn/
  icp:
    enable: false
    number:
    url:

inject:
  enable: false
  head:
    -
    -
  footer:
    -
    -

plugins:
  #  $ npm i hexo-generator-feed
  feed:
    enable: false
  aplayer:
    enable: false
    type: fixed # fixed, mini
    audios:
      - name:
        artist:
        url:
        cover:
        lrc:
  #  $ npm i hexo-filter-mermaid-diagrams
  mermaid:
    enable: false
    version: "11.4.1"

page_templates:
  friends_column: 3
  tags_style: blur # blur, cloud
  bookmarks_column: 3

cdn:
  enable: false
  provider: npmmirror # npmmirror, zstatic, cdnjs, jsdelivr, unpkg, custom
  custom_url:
# Custom CDN URL
# format example: https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
# The ${path} must leads to the root of the "source" folder of the theme

developer:
  enable: false
